export const SET_TYPE_SELECTED = 'SET_TYPE_SELECTED';
export const SET_SORTBY_SELECTED = 'SET_SORTBY_SELECTED';

export const SET_RELOAD = 'SET_RELOAD';

export const SET_MOVIE_SELECTED = 'SET_MOVIE_SELECTED';

export const CHANGE_STATE_MORE_INFO_MODAL = 'CHANGE_STATE_MORE_INFO_MODAL';

export const GET_MOVIES_START = 'GET_MOVIES_START';
export const GET_MOVIES_SUCCESS  = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_ERROR  = 'GET_MOVIES_ERROR';

export const CREATE_MOVIE_START  = 'CREATE_MOVIE_START';
export const CREATE_MOVIE_SUCCESS  = 'CREATE_MOVIE_SUCCESS';
export const CREATE_MOVIE_ERROR  = 'CREATE_MOVIE_ERROR';

export const EDIT_MOVIE_START  = 'EDIT_MOVIE_START';
export const EDIT_MOVIE_SUCCESS  = 'EDIT_MOVIE_SUCCESS';
export const EDIT_MOVIE_ERROR  = 'EDIT_MOVIE_ERROR';

export const DELETE_MOVIE_START  = 'DELETE_MOVIE_START';
export const DELETE_MOVIE_SUCCESS  = 'DELETE_MOVIE_SUCCESS';
export const DELETE_MOVIE_ERROR  = 'DELETE_MOVIE_ERROR';

export const CLEAR_MESSAGES  = 'CLEAR_MESSAGES';